/**
 * Centralized Studio model catalog used by selectors and node controls.
 * Includes generation + advanced workflows with defaults and capability hints.
 */

export type StudioModelMediaType = 'text' | 'image' | 'video' | 'audio';
export type StudioModelUiGroup = 'generation' | 'advanced';

export interface StudioModel {
  id: string;
  name: string;
  description: string;
  credits: number;
  time: string;
  icon: string;
  badge?: 'Free' | 'Premium' | 'Fast' | 'Quality';
  provider: 'fal-ai' | 'lovable-ai';
  category: string;
  mediaType: StudioModelMediaType;
  workflowType: string;
  uiGroup: StudioModelUiGroup;
  supports?: string[];
  defaults?: Record<string, unknown>;
}

const imageGenerationModels: StudioModel[] = [
  {
    id: 'fal-ai/flux/schnell',
    name: 'FLUX Schnell',
    description: 'Legacy fast image generation.',
    credits: 3,
    time: '~3s',
    icon: 'image',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'image_size', 'num_images'],
    defaults: { image_size: 'landscape_16_9', num_images: 1, num_inference_steps: 4 },
  },
  {
    id: 'fal-ai/flux/dev',
    name: 'FLUX Dev',
    description: 'Legacy quality image generation.',
    credits: 5,
    time: '~8s',
    icon: 'image',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'image_size', 'num_images', 'guidance_scale', 'num_inference_steps'],
    defaults: { image_size: 'landscape_16_9', num_images: 1, guidance_scale: 3.5, num_inference_steps: 28 },
  },
  {
    id: 'fal-ai/flux-pro/v1.1-ultra',
    name: 'FLUX Pro Ultra',
    description: 'Legacy pro image model.',
    credits: 8,
    time: '~10s',
    icon: 'image',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/nano-banana-pro',
    name: 'Nano Banana Pro',
    description: 'Gemini 3 Pro image model.',
    credits: 7,
    time: '~8s',
    icon: 'image',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'num_images', 'aspect_ratio', 'resolution', 'output_format', 'safety_tolerance'],
    defaults: { num_images: 1, aspect_ratio: 'auto', output_format: 'png', resolution: '2K' },
  },
  {
    id: 'fal-ai/nano-banana-2',
    name: 'Nano Banana 2',
    description: 'Fast image generation and editing.',
    credits: 4,
    time: '~4s',
    icon: 'image',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'num_images', 'aspect_ratio', 'output_format', 'safety_tolerance'],
    defaults: { num_images: 1, aspect_ratio: 'auto', output_format: 'png' },
  },
  {
    id: 'fal-ai/qwen-image-2/text-to-image',
    name: 'Qwen Image 2',
    description: 'Unified high-quality text-to-image.',
    credits: 5,
    time: '~7s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'num_images', 'aspect_ratio', 'output_format'],
    defaults: { num_images: 1, aspect_ratio: '16:9', output_format: 'png' },
  },
  {
    id: 'fal-ai/qwen-image-2/pro/text-to-image',
    name: 'Qwen Image 2 Pro',
    description: 'Higher-fidelity Qwen image model.',
    credits: 7,
    time: '~10s',
    icon: 'image',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'num_images', 'aspect_ratio', 'output_format'],
    defaults: { num_images: 1, aspect_ratio: '16:9', output_format: 'png' },
  },
  {
    id: 'fal-ai/qwen-image-2512',
    name: 'Qwen Image 2512',
    description: 'Enhanced text rendering and natural textures.',
    credits: 6,
    time: '~8s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'num_images'],
    defaults: { num_images: 1 },
  },
  {
    id: 'fal-ai/seedream/v5/lite/text-to-image',
    name: 'Seedream 5 Lite',
    description: 'Reliable high-quality image generation.',
    credits: 5,
    time: '~8s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'num_images', 'aspect_ratio'],
    defaults: { num_images: 1, aspect_ratio: 'auto' },
  },
  {
    id: 'fal-ai/ideogram/v3',
    name: 'Ideogram V3',
    description: 'Strong typography and design output.',
    credits: 5,
    time: '~8s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/stable-diffusion-v35-large',
    name: 'Stable Diffusion 3.5 Large',
    description: 'High-fidelity open-source image generation.',
    credits: 4,
    time: '~6s',
    icon: 'image',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'image_size', 'num_images'],
    defaults: { image_size: 'landscape_16_9', num_images: 1 },
  },
  {
    id: 'fal-ai/recraft-v3',
    name: 'Recraft V3',
    description: 'Design-focused generation with strong typography.',
    credits: 5,
    time: '~7s',
    icon: 'image',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'image_size'],
    defaults: { image_size: 'landscape_16_9' },
  },
  {
    id: 'fal-ai/aura-flow',
    name: 'AuraFlow',
    description: 'Fast open-source flow-matching model.',
    credits: 3,
    time: '~5s',
    icon: 'image',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'num_images'],
    defaults: { num_images: 1 },
  },
  {
    id: 'fal-ai/hidream-i1-full',
    name: 'HiDream I1',
    description: 'Premium quality with rich detail.',
    credits: 6,
    time: '~10s',
    icon: 'image',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'image_size', 'num_images'],
    defaults: { image_size: 'landscape_16_9', num_images: 1 },
  },
  {
    id: 'fal-ai/omnigen-v1',
    name: 'OmniGen V1',
    description: 'Multi-modal unified generation model.',
    credits: 5,
    time: '~8s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'image_size'],
    defaults: { image_size: 'landscape_16_9' },
  },
  // ── New Image Generation Models ──
  {
    id: 'fal-ai/flux-2-pro',
    name: 'Flux 2 Pro',
    description: 'Premium next-gen FLUX image generation.',
    credits: 8,
    time: '~10s',
    icon: 'image',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio', 'num_images'],
    defaults: { aspect_ratio: '16:9', num_images: 1 },
  },
  {
    id: 'fal-ai/flux-2',
    name: 'Flux 2',
    description: 'High-quality FLUX 2 image generation.',
    credits: 6,
    time: '~7s',
    icon: 'image',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio', 'num_images'],
    defaults: { aspect_ratio: '16:9', num_images: 1 },
  },
  {
    id: 'fal-ai/flux-2/turbo',
    name: 'Flux 2 Turbo',
    description: 'Fast FLUX 2 image generation.',
    credits: 5,
    time: '~4s',
    icon: 'image',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio', 'num_images'],
    defaults: { aspect_ratio: '16:9', num_images: 1 },
  },
  {
    id: 'fal-ai/flux-2/flash',
    name: 'Flux 2 Flash',
    description: 'Ultra-fast FLUX 2 image generation.',
    credits: 4,
    time: '~3s',
    icon: 'image',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio', 'num_images'],
    defaults: { aspect_ratio: '16:9', num_images: 1 },
  },
  {
    id: 'fal-ai/flux-2-max',
    name: 'Flux 2 Max',
    description: 'Maximum quality FLUX 2 generation.',
    credits: 10,
    time: '~12s',
    icon: 'image',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio', 'num_images'],
    defaults: { aspect_ratio: '16:9', num_images: 1 },
  },
  {
    id: 'fal-ai/flux-2-flex',
    name: 'Flux 2 Flex',
    description: 'Flexible FLUX 2 generation with editing.',
    credits: 6,
    time: '~7s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio', 'num_images'],
    defaults: { aspect_ratio: '16:9', num_images: 1 },
  },
  {
    id: 'fal-ai/flux-pro/kontext/text-to-image',
    name: 'FLUX Kontext Pro',
    description: 'Context-aware FLUX Pro generation.',
    credits: 7,
    time: '~9s',
    icon: 'image',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/gpt-image-1.5',
    name: 'GPT-Image 1.5',
    description: 'OpenAI GPT-powered image generation.',
    credits: 8,
    time: '~10s',
    icon: 'image',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'num_images'],
    defaults: { num_images: 1 },
  },
  {
    id: 'xai/grok-imagine-image',
    name: 'Grok Imagine Image',
    description: 'xAI Grok-powered image generation.',
    credits: 7,
    time: '~8s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt'],
    defaults: {},
  },
  {
    id: 'fal-ai/imagen4/preview',
    name: 'Imagen 4',
    description: 'Google Imagen 4 image generation.',
    credits: 7,
    time: '~8s',
    icon: 'image',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/imagen4/preview/ultra',
    name: 'Imagen 4 Ultra',
    description: 'Highest quality Google Imagen 4.',
    credits: 10,
    time: '~12s',
    icon: 'image',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/imagen4/preview/fast',
    name: 'Imagen 4 Fast',
    description: 'Fast Google Imagen 4 generation.',
    credits: 5,
    time: '~4s',
    icon: 'image',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/bytedance/seedream/v4.5/text-to-image',
    name: 'Seedream 4.5',
    description: 'ByteDance Seedream image generation.',
    credits: 5,
    time: '~7s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: 'auto' },
  },
  {
    id: 'fal-ai/z-image/turbo',
    name: 'Z-Image Turbo',
    description: 'Ultra-fast lightweight image generation.',
    credits: 4,
    time: '~3s',
    icon: 'image',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'image-generation',
    mediaType: 'image',
    workflowType: 'text-to-image',
    uiGroup: 'generation',
    supports: ['prompt', 'num_images'],
    defaults: { num_images: 1 },
  },
];

const imageAdvancedModels: StudioModel[] = [
  {
    id: 'fal-ai/nano-banana-pro/edit',
    name: 'Nano Banana Pro Edit',
    description: 'Natural-language image editing.',
    credits: 8,
    time: '~10s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'image_urls', 'num_images', 'aspect_ratio', 'output_format'],
    defaults: { num_images: 1, aspect_ratio: 'auto', output_format: 'png' },
  },
  {
    id: 'fal-ai/nano-banana-2/edit',
    name: 'Nano Banana 2 Edit',
    description: 'Fast image editing.',
    credits: 5,
    time: '~6s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'image_urls', 'num_images', 'aspect_ratio', 'output_format'],
    defaults: { num_images: 1, aspect_ratio: 'auto', output_format: 'png' },
  },
  {
    id: 'fal-ai/qwen-image-2/edit',
    name: 'Qwen Image 2 Edit',
    description: 'Natural-language editing with Qwen.',
    credits: 6,
    time: '~9s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'image_urls', 'output_format'],
    defaults: { output_format: 'png' },
  },
  {
    id: 'fal-ai/qwen-image-2/pro/edit',
    name: 'Qwen Image 2 Pro Edit',
    description: 'Precision image editing (pro).',
    credits: 8,
    time: '~12s',
    icon: 'image',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'image_urls', 'output_format'],
    defaults: { output_format: 'png' },
  },
  {
    id: 'fal-ai/qwen-image-edit-2509',
    name: 'Qwen Image Edit 2509',
    description: 'Advanced image editing plus workflow.',
    credits: 7,
    time: '~10s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'image_urls'],
    defaults: {},
  },
  {
    id: 'fal-ai/qwen-image-layered',
    name: 'Qwen Image Layered',
    description: 'Decompose image into RGBA layers.',
    credits: 6,
    time: '~8s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-analysis',
    uiGroup: 'advanced',
    supports: ['image_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/qwen-image-edit-2511-multiple-angles',
    name: 'Qwen Multiple Angles 2511',
    description: 'Generate alternate camera viewpoints.',
    credits: 7,
    time: '~10s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['image_urls', 'horizontal_angle', 'vertical_angle', 'zoom'],
    defaults: {},
  },
  {
    id: 'fal-ai/qwen-image-edit-plus-lora-gallery/multiple-angles',
    name: 'Qwen LoRA Multiple Angles',
    description: 'LoRA multiple-angle camera controls.',
    credits: 7,
    time: '~10s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['image_urls', 'horizontal_angle', 'vertical_angle', 'zoom'],
    defaults: {},
  },
  {
    id: 'fal-ai/seedream/v5/lite/edit',
    name: 'Seedream 5 Lite Edit',
    description: 'Natural-language image editing.',
    credits: 6,
    time: '~9s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'image_urls'],
    defaults: {},
  },
  {
    id: 'fal-ai/seedream/v4.5/edit',
    name: 'Seedream 4.5 Edit',
    description: 'Image generation/editing hybrid.',
    credits: 6,
    time: '~9s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'image_urls', 'aspect_ratio'],
    defaults: { aspect_ratio: 'auto' },
  },
  {
    id: 'fal-ai/flux/dev/image-to-image',
    name: 'FLUX Dev Image-to-Image',
    description: 'Transform existing images with FLUX Dev.',
    credits: 6,
    time: '~8s',
    icon: 'image',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-to-image',
    uiGroup: 'advanced',
    supports: ['prompt', 'image_url', 'strength'],
    defaults: { strength: 0.75 },
  },
  {
    id: 'fal-ai/flux-pro/v1.1-ultra/redux',
    name: 'FLUX Pro Ultra Redux',
    description: 'Premium image variation and remix.',
    credits: 9,
    time: '~12s',
    icon: 'image',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-to-image',
    uiGroup: 'advanced',
    supports: ['prompt', 'image_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/iclight-v2',
    name: 'IC-Light V2 (Relighting)',
    description: 'AI-powered scene relighting.',
    credits: 5,
    time: '~7s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'image_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/creative-upscaler',
    name: 'Creative Upscaler',
    description: 'AI upscaling with creative enhancement.',
    credits: 4,
    time: '~6s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['image_url', 'scale'],
    defaults: { scale: 2 },
  },
  {
    id: 'fal-ai/clarity-upscaler',
    name: 'Clarity Upscaler',
    description: 'High-clarity detail-preserving upscaler.',
    credits: 4,
    time: '~6s',
    icon: 'image',
    provider: 'fal-ai',
    category: 'image-editing',
    mediaType: 'image',
    workflowType: 'image-edit',
    uiGroup: 'advanced',
    supports: ['image_url', 'scale'],
    defaults: { scale: 2 },
  },
];

const videoGenerationModels: StudioModel[] = [
  {
    id: 'fal-ai/kling-video/o3/standard/text-to-video',
    name: 'Kling O3 Standard T2V',
    description: 'Balanced Omni text-to-video generation.',
    credits: 20,
    time: '~45s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration', 'aspect_ratio', 'generate_audio'],
    defaults: { duration: '5', aspect_ratio: '16:9', generate_audio: true },
  },
  {
    id: 'fal-ai/kling-video/o3/pro/text-to-video',
    name: 'Kling O3 Pro T2V',
    description: 'Higher-fidelity Omni text-to-video.',
    credits: 30,
    time: '~90s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration', 'aspect_ratio', 'generate_audio'],
    defaults: { duration: '8', aspect_ratio: '16:9', generate_audio: true },
  },
  {
    id: 'fal-ai/kling-video/o3/standard/image-to-video',
    name: 'Kling O3 Standard I2V',
    description: 'Image-to-video with stable motion.',
    credits: 24,
    time: '~60s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'duration', 'generate_audio'],
    defaults: { duration: '5', generate_audio: false },
  },
  {
    id: 'fal-ai/kling-video/o3/pro/image-to-video',
    name: 'Kling O3 Pro I2V',
    description: 'Pro image-to-video quality and motion.',
    credits: 32,
    time: '~100s',
    icon: 'video',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'duration', 'generate_audio'],
    defaults: { duration: '5', generate_audio: true },
  },
  {
    id: 'fal-ai/kling-video/v3/pro/image-to-video',
    name: 'Kling 3.0 Pro I2V',
    description: 'Cinematic image-to-video with audio.',
    credits: 30,
    time: '~90s',
    icon: 'video',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'duration_seconds', 'fps', 'generate_audio'],
    defaults: { duration_seconds: 5, fps: 24, generate_audio: true },
  },
  {
    id: 'fal-ai/kling-video/v2.5-turbo/pro/image-to-video',
    name: 'Kling 2.5 Turbo Pro I2V',
    description: 'Fast image-to-video with fluid motion.',
    credits: 22,
    time: '~55s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'duration_seconds', 'fps'],
    defaults: { duration_seconds: 4, fps: 24 },
  },
  {
    id: 'fal-ai/kling-video/o1/image-to-video',
    name: 'Kling O1 FLFV I2V',
    description: 'Start/end frame image-to-video.',
    credits: 28,
    time: '~75s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'start_image_url', 'end_image_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/sora-2/text-to-video',
    name: 'Sora 2',
    description: 'Detailed text-to-video generation.',
    credits: 35,
    time: '~120s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/sora-2/text-to-video/pro',
    name: 'Sora 2 Pro',
    description: 'High-fidelity pro text-to-video.',
    credits: 50,
    time: '~150s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/bytedance/seedance/v1/lite/text-to-video',
    name: 'Seedance Lite T2V',
    description: 'Lite text-to-video generation.',
    credits: 18,
    time: '~45s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/bytedance/seedance/v1/lite/image-to-video',
    name: 'Seedance Lite I2V',
    description: 'Lite image-to-video generation.',
    credits: 20,
    time: '~50s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['image_url', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/bytedance/seedance/v1/pro/text-to-video',
    name: 'Seedance Pro T2V',
    description: '1080p pro text-to-video.',
    credits: 30,
    time: '~80s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/bytedance/seedance/v1/pro/image-to-video',
    name: 'Seedance Pro I2V',
    description: '1080p pro image-to-video.',
    credits: 32,
    time: '~90s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['image_url', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/ltx-2-19b/text-to-video',
    name: 'LTX 2 19B T2V',
    description: 'Text-to-video generation with audio.',
    credits: 24,
    time: '~70s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds'],
    defaults: { duration_seconds: 4 },
  },
  {
    id: 'fal-ai/ltx-video',
    name: 'LTX Video',
    description: 'General fast text-to-video.',
    credits: 16,
    time: '~40s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt'],
    defaults: {},
  },
  {
    id: 'fal-ai/magi',
    name: 'MAGI T2V',
    description: 'Legacy text-to-video compatibility model.',
    credits: 20,
    time: '~50s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio', 'duration'],
    defaults: { aspect_ratio: '16:9', duration: '5s' },
  },
  {
    id: 'fal-ai/magi/image-to-video',
    name: 'MAGI I2V',
    description: 'Legacy image-to-video compatibility model.',
    credits: 22,
    time: '~60s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'aspect_ratio', 'duration'],
    defaults: { aspect_ratio: '16:9', duration: '5s' },
  },
  {
    id: 'fal-ai/minimax/video-01-live',
    name: 'MiniMax Video-01 Live',
    description: 'Real-time quality video generation.',
    credits: 25,
    time: '~60s',
    icon: 'video',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/minimax/video-01/image-to-video',
    name: 'MiniMax Video-01 I2V',
    description: 'Image-to-video with MiniMax quality.',
    credits: 28,
    time: '~75s',
    icon: 'video',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/hunyuan-video',
    name: 'HunyuanVideo',
    description: 'Tencent open-source video generation.',
    credits: 22,
    time: '~65s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/wan/v2.1/1.3b/text-to-video',
    name: 'Wan 2.1 T2V',
    description: 'Fast lightweight text-to-video.',
    credits: 18,
    time: '~50s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio', 'duration'],
    defaults: { aspect_ratio: '16:9', duration: '5s' },
  },
  {
    id: 'fal-ai/wan/v2.1/1.3b/image-to-video',
    name: 'Wan 2.1 I2V',
    description: 'Lightweight image-to-video generation.',
    credits: 20,
    time: '~55s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/cogvideox-5b',
    name: 'CogVideoX-5B',
    description: 'Open-source video generation model.',
    credits: 20,
    time: '~55s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt'],
    defaults: {},
  },
  {
    id: 'fal-ai/vidu/v2.5/text-to-video',
    name: 'Vidu V2.5 T2V',
    description: 'High-quality text-to-video from Vidu.',
    credits: 24,
    time: '~70s',
    icon: 'video',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/vidu/v2.5/image-to-video',
    name: 'Vidu V2.5 I2V',
    description: 'Image-to-video with Vidu quality.',
    credits: 26,
    time: '~80s',
    icon: 'video',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  // ── New Video Generation Models ──
  {
    id: 'fal-ai/veo3.1',
    name: 'Veo 3.1',
    description: 'Google Veo 3.1 premium text-to-video.',
    credits: 40,
    time: '~120s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds', 'aspect_ratio'],
    defaults: { duration_seconds: 8, aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/veo3.1/fast',
    name: 'Veo 3.1 Fast',
    description: 'Fast Google Veo 3.1 generation.',
    credits: 30,
    time: '~60s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds', 'aspect_ratio'],
    defaults: { duration_seconds: 5, aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/veo3.1/lite',
    name: 'Veo 3.1 Lite',
    description: 'Lightweight Google Veo 3.1.',
    credits: 22,
    time: '~45s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/veo3',
    name: 'Veo 3',
    description: 'Google Veo 3 high-quality video.',
    credits: 35,
    time: '~100s',
    icon: 'video',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/veo3/fast',
    name: 'Veo 3 Fast',
    description: 'Fast Google Veo 3 generation.',
    credits: 25,
    time: '~50s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/kling-video/v3/pro/text-to-video',
    name: 'Kling 3.0 Pro T2V',
    description: 'Kling 3.0 Pro cinematic text-to-video.',
    credits: 32,
    time: '~90s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds', 'aspect_ratio', 'generate_audio'],
    defaults: { duration_seconds: 5, aspect_ratio: '16:9', generate_audio: true },
  },
  {
    id: 'fal-ai/kling-video/v3/standard/text-to-video',
    name: 'Kling 3.0 Std T2V',
    description: 'Kling 3.0 Standard text-to-video.',
    credits: 22,
    time: '~55s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds', 'aspect_ratio'],
    defaults: { duration_seconds: 5, aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/kling-video/v2.6/pro/text-to-video',
    name: 'Kling 2.6 Pro T2V',
    description: 'Kling 2.6 Pro text-to-video.',
    credits: 28,
    time: '~80s',
    icon: 'video',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds', 'aspect_ratio'],
    defaults: { duration_seconds: 5, aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/bytedance/seedance/v1.5/pro/text-to-video',
    name: 'Seedance 1.5 Pro T2V',
    description: 'ByteDance Seedance 1.5 Pro text-to-video.',
    credits: 32,
    time: '~90s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'xai/grok-imagine-video/text-to-video',
    name: 'Grok Imagine Video',
    description: 'xAI Grok-powered video generation.',
    credits: 30,
    time: '~80s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt'],
    defaults: {},
  },
  {
    id: 'fal-ai/minimax/hailuo-02/standard/text-to-video',
    name: 'Hailuo 02 Std T2V',
    description: 'MiniMax Hailuo 02 Standard text-to-video.',
    credits: 24,
    time: '~65s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/minimax/hailuo-02/pro/text-to-video',
    name: 'Hailuo 02 Pro T2V',
    description: 'MiniMax Hailuo 02 Pro text-to-video.',
    credits: 32,
    time: '~90s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/pixverse/v6/text-to-video',
    name: 'Pixverse V6 T2V',
    description: 'Pixverse V6 text-to-video generation.',
    credits: 20,
    time: '~50s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt'],
    defaults: {},
  },
  {
    id: 'fal-ai/ltx-2.3/text-to-video',
    name: 'LTX 2.3 Pro T2V',
    description: 'LTX 2.3 Pro text-to-video.',
    credits: 22,
    time: '~60s',
    icon: 'video',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/ltx-2.3/text-to-video/fast',
    name: 'LTX 2.3 Fast T2V',
    description: 'Fast LTX 2.3 text-to-video.',
    credits: 16,
    time: '~35s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'duration_seconds'],
    defaults: { duration_seconds: 4 },
  },
  {
    id: 'fal-ai/wan/v2.2-a14b/text-to-video',
    name: 'Wan 2.2 T2V',
    description: 'Wan 2.2 text-to-video generation.',
    credits: 20,
    time: '~55s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'text-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'aspect_ratio'],
    defaults: { aspect_ratio: '16:9' },
  },
  // ── New Image-to-Video Models ──
  {
    id: 'fal-ai/veo3.1/image-to-video',
    name: 'Veo 3.1 I2V',
    description: 'Google Veo 3.1 image-to-video.',
    credits: 42,
    time: '~130s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/veo3.1/fast/image-to-video',
    name: 'Veo 3.1 Fast I2V',
    description: 'Fast Google Veo 3.1 image-to-video.',
    credits: 32,
    time: '~70s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/veo3.1/lite/image-to-video',
    name: 'Veo 3.1 Lite I2V',
    description: 'Lightweight Google Veo 3.1 image-to-video.',
    credits: 24,
    time: '~50s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/kling-video/v2.6/pro/image-to-video',
    name: 'Kling 2.6 Pro I2V',
    description: 'Kling 2.6 Pro image-to-video.',
    credits: 30,
    time: '~85s',
    icon: 'video',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/sora-2/image-to-video',
    name: 'Sora 2 I2V',
    description: 'OpenAI Sora 2 image-to-video.',
    credits: 38,
    time: '~120s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/bytedance/seedance/v1.5/pro/image-to-video',
    name: 'Seedance 1.5 Pro I2V',
    description: 'ByteDance Seedance 1.5 Pro image-to-video.',
    credits: 34,
    time: '~95s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['image_url', 'duration_seconds'],
    defaults: { duration_seconds: 5 },
  },
  {
    id: 'fal-ai/minimax/hailuo-02/standard/image-to-video',
    name: 'Hailuo 02 Std I2V',
    description: 'MiniMax Hailuo 02 Standard image-to-video.',
    credits: 26,
    time: '~70s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/minimax/hailuo-02/pro/image-to-video',
    name: 'Hailuo 02 Pro I2V',
    description: 'MiniMax Hailuo 02 Pro image-to-video.',
    credits: 34,
    time: '~95s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-generation',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'generation',
    supports: ['prompt', 'image_url'],
    defaults: {},
  },
];

const videoAdvancedModels: StudioModel[] = [
  {
    id: 'fal-ai/kling-video/o3/standard/reference-to-video',
    name: 'Kling O3 Standard Reference',
    description: 'Reference-guided video generation.',
    credits: 28,
    time: '~80s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-editing',
    mediaType: 'video',
    workflowType: 'reference-to-video',
    uiGroup: 'advanced',
    supports: ['prompt', 'start_image_url', 'image_urls', 'elements'],
    defaults: {},
  },
  {
    id: 'fal-ai/kling-video/o3/pro/reference-to-video',
    name: 'Kling O3 Pro Reference',
    description: 'Pro reference-to-video with element controls.',
    credits: 38,
    time: '~120s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-editing',
    mediaType: 'video',
    workflowType: 'reference-to-video',
    uiGroup: 'advanced',
    supports: ['prompt', 'start_image_url', 'image_urls', 'elements', 'duration', 'aspect_ratio'],
    defaults: { duration: '8', aspect_ratio: '16:9' },
  },
  {
    id: 'fal-ai/kling-video/o3/standard/video-to-video/edit',
    name: 'Kling O3 Standard V2V Edit',
    description: 'Standard video-to-video editing.',
    credits: 28,
    time: '~90s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-editing',
    mediaType: 'video',
    workflowType: 'video-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'video_url', 'image_urls', 'elements'],
    defaults: {},
  },
  {
    id: 'fal-ai/kling-video/o3/pro/video-to-video/edit',
    name: 'Kling O3 Pro V2V Edit',
    description: 'Pro video editing with references/elements.',
    credits: 40,
    time: '~140s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'video-editing',
    mediaType: 'video',
    workflowType: 'video-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'video_url', 'image_urls', 'elements', 'keep_audio'],
    defaults: { keep_audio: true },
  },
  {
    id: 'fal-ai/kling-video/o3/pro/video-to-video/reference',
    name: 'Kling O3 Pro V2V Reference',
    description: 'Reference-driven video to video workflow.',
    credits: 38,
    time: '~130s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-editing',
    mediaType: 'video',
    workflowType: 'video-reference',
    uiGroup: 'advanced',
    supports: ['prompt', 'video_url', 'image_urls', 'elements'],
    defaults: {},
  },
  {
    id: 'fal-ai/kling-video/o1/reference-to-video',
    name: 'Kling O1 Reference I2V',
    description: 'Reference-based O1 image-to-video.',
    credits: 32,
    time: '~100s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-editing',
    mediaType: 'video',
    workflowType: 'reference-to-video',
    uiGroup: 'advanced',
    supports: ['prompt', 'reference_image_url', 'start_image_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/kling-video/o1/video-to-video/edit',
    name: 'Kling O1 V2V Edit',
    description: 'Video-to-video edit for O1.',
    credits: 30,
    time: '~100s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-editing',
    mediaType: 'video',
    workflowType: 'video-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'video_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/sora-2/video-to-video/remix',
    name: 'Sora 2 Remix',
    description: 'Prompt + reference video remixing.',
    credits: 36,
    time: '~110s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-editing',
    mediaType: 'video',
    workflowType: 'video-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'video_url', 'image_urls'],
    defaults: {},
  },
  {
    id: 'fal-ai/ltx-2-19b/distilled/extend-video',
    name: 'LTX Extend Video',
    description: 'Extend an existing video clip.',
    credits: 22,
    time: '~70s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-editing',
    mediaType: 'video',
    workflowType: 'video-edit',
    uiGroup: 'advanced',
    supports: ['prompt', 'video_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/ffmpeg-api/compose',
    name: 'FFmpeg Compose',
    description: 'Compose timeline from multiple media inputs.',
    credits: 12,
    time: '~20s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-utility',
    mediaType: 'video',
    workflowType: 'video-compose',
    uiGroup: 'advanced',
    supports: ['videos', 'images', 'audio', 'timeline'],
    defaults: {},
  },
  {
    id: 'fal-ai/ffmpeg-api/merge-videos',
    name: 'FFmpeg Merge Videos',
    description: 'Merge two or more video files.',
    credits: 10,
    time: '~18s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-utility',
    mediaType: 'video',
    workflowType: 'video-to-video',
    uiGroup: 'advanced',
    supports: ['video_urls'],
    defaults: {},
  },
  {
    id: 'fal-ai/ffmpeg-api/merge-audio-video',
    name: 'FFmpeg Merge Audio+Video',
    description: 'Combine audio with video tracks.',
    credits: 10,
    time: '~18s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-utility',
    mediaType: 'video',
    workflowType: 'video-to-video',
    uiGroup: 'advanced',
    supports: ['video_urls', 'audio_urls'],
    defaults: {},
  },
  {
    id: 'fal-ai/ffmpeg-api/extract-frame',
    name: 'FFmpeg Extract Frame',
    description: 'Extract first/middle/last frame from video.',
    credits: 6,
    time: '~8s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-utility',
    mediaType: 'video',
    workflowType: 'video-to-image',
    uiGroup: 'advanced',
    supports: ['video_url', 'frame_position'],
    defaults: { frame_position: 'middle' },
  },
  {
    id: 'fal-ai/workflow-utilities/trim-video',
    name: 'Trim Video',
    description: 'Trim video to a selected time range.',
    credits: 8,
    time: '~10s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-utility',
    mediaType: 'video',
    workflowType: 'video-to-video',
    uiGroup: 'advanced',
    supports: ['video_url', 'start_time', 'end_time'],
    defaults: {},
  },
  {
    id: 'fal-ai/workflow-utilities/scale-video',
    name: 'Scale Video',
    description: 'Scale video to target dimensions.',
    credits: 8,
    time: '~10s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-utility',
    mediaType: 'video',
    workflowType: 'video-to-video',
    uiGroup: 'advanced',
    supports: ['video_url', 'width', 'height'],
    defaults: {},
  },
  {
    id: 'fal-ai/workflow-utilities/reverse-video',
    name: 'Reverse Video',
    description: 'Reverse a source video.',
    credits: 8,
    time: '~10s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-utility',
    mediaType: 'video',
    workflowType: 'video-to-video',
    uiGroup: 'advanced',
    supports: ['video_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/workflow-utilities/extract-nth-frame',
    name: 'Extract Nth Frame',
    description: 'Extract every Nth frame from video.',
    credits: 7,
    time: '~9s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-utility',
    mediaType: 'video',
    workflowType: 'video-to-image',
    uiGroup: 'advanced',
    supports: ['video_url', 'nth'],
    defaults: { nth: 10 },
  },
  {
    id: 'fal-ai/workflow-utilities/blend-video',
    name: 'Blend Video',
    description: 'Blend two videos.',
    credits: 10,
    time: '~15s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-utility',
    mediaType: 'video',
    workflowType: 'video-to-video',
    uiGroup: 'advanced',
    supports: ['video_url_a', 'video_url_b'],
    defaults: {},
  },
  {
    id: 'fal-ai/workflow-utilities/interleave-video',
    name: 'Interleave Video',
    description: 'Interleave multiple videos.',
    credits: 10,
    time: '~15s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-utility',
    mediaType: 'video',
    workflowType: 'video-to-video',
    uiGroup: 'advanced',
    supports: ['video_urls'],
    defaults: {},
  },
  {
    id: 'fal-ai/ffmpeg-api/metadata',
    name: 'FFmpeg Metadata',
    description: 'Inspect media encoding metadata.',
    credits: 4,
    time: '~4s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-utility',
    mediaType: 'video',
    workflowType: 'analysis',
    uiGroup: 'advanced',
    supports: ['url'],
    defaults: {},
  },
  {
    id: 'fal-ai/kling-video/o3/standard/video-extend',
    name: 'Kling O3 Video Extend',
    description: 'Extend video clips with AI continuation.',
    credits: 26,
    time: '~85s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'video-editing',
    mediaType: 'video',
    workflowType: 'video-to-video',
    uiGroup: 'advanced',
    supports: ['video_url', 'prompt'],
    defaults: {},
  },
  {
    id: 'fal-ai/stable-video',
    name: 'Stable Video Diffusion',
    description: 'Image-to-video via Stability AI.',
    credits: 16,
    time: '~40s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'video-editing',
    mediaType: 'video',
    workflowType: 'image-to-video',
    uiGroup: 'advanced',
    supports: ['image_url'],
    defaults: {},
  },
];

export const IMAGE_MODELS: StudioModel[] = [...imageGenerationModels, ...imageAdvancedModels];
export const VIDEO_MODELS: StudioModel[] = [...videoGenerationModels, ...videoAdvancedModels];

export const AUDIO_MODELS: StudioModel[] = [
  {
    id: 'fal-ai/ffmpeg-api/merge-audios',
    name: 'FFmpeg Merge Audios',
    description: 'Merge multiple audio tracks.',
    credits: 8,
    time: '~12s',
    icon: 'audio',
    provider: 'fal-ai',
    category: 'audio-utility',
    mediaType: 'audio',
    workflowType: 'audio-to-audio',
    uiGroup: 'advanced',
    supports: ['audio_urls'],
    defaults: {},
  },
  {
    id: 'fal-ai/ffmpeg-api/loudnorm',
    name: 'FFmpeg Loudnorm',
    description: 'EBU R128 loudness normalization.',
    credits: 6,
    time: '~10s',
    icon: 'audio',
    provider: 'fal-ai',
    category: 'audio-utility',
    mediaType: 'audio',
    workflowType: 'analysis',
    uiGroup: 'advanced',
    supports: ['audio_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/ffmpeg-api/waveform',
    name: 'FFmpeg Waveform',
    description: 'Waveform extraction and analysis.',
    credits: 4,
    time: '~5s',
    icon: 'audio',
    provider: 'fal-ai',
    category: 'audio-utility',
    mediaType: 'audio',
    workflowType: 'analysis',
    uiGroup: 'advanced',
    supports: ['audio_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/workflow-utilities/audio-compressor',
    name: 'Audio Compressor',
    description: 'Dynamic compression for audio.',
    credits: 6,
    time: '~10s',
    icon: 'audio',
    provider: 'fal-ai',
    category: 'audio-utility',
    mediaType: 'audio',
    workflowType: 'audio-to-audio',
    uiGroup: 'advanced',
    supports: ['audio_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/workflow-utilities/impulse-response',
    name: 'Impulse Response',
    description: 'Apply impulse response to audio.',
    credits: 6,
    time: '~10s',
    icon: 'audio',
    provider: 'fal-ai',
    category: 'audio-utility',
    mediaType: 'audio',
    workflowType: 'audio-to-audio',
    uiGroup: 'advanced',
    supports: ['audio_url', 'impulse_url'],
    defaults: {},
  },
];

export const LIPSYNC_MODELS: StudioModel[] = [
  {
    id: 'fal-ai/kling-video/o3/pro/lip-sync',
    name: 'Kling O3 Pro Lip Sync',
    description: 'Premium audio-driven lip sync.',
    credits: 30,
    time: '~90s',
    icon: 'video',
    badge: 'Premium',
    provider: 'fal-ai',
    category: 'lip-sync',
    mediaType: 'video',
    workflowType: 'lip-sync',
    uiGroup: 'generation',
    supports: ['audio_url', 'image_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/kling-video/v2.5-turbo/lip-sync',
    name: 'Kling 2.5 Turbo Lip Sync',
    description: 'Fast turbo lip sync generation.',
    credits: 22,
    time: '~55s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'lip-sync',
    mediaType: 'video',
    workflowType: 'lip-sync',
    uiGroup: 'generation',
    supports: ['audio_url', 'image_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/sadtalker',
    name: 'SadTalker',
    description: 'Audio-driven talking head generation.',
    credits: 12,
    time: '~30s',
    icon: 'video',
    badge: 'Fast',
    provider: 'fal-ai',
    category: 'lip-sync',
    mediaType: 'video',
    workflowType: 'lip-sync',
    uiGroup: 'generation',
    supports: ['audio_url', 'image_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/liveportrait',
    name: 'LivePortrait',
    description: 'Expression-driven portrait animation.',
    credits: 15,
    time: '~40s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'lip-sync',
    mediaType: 'video',
    workflowType: 'lip-sync',
    uiGroup: 'generation',
    supports: ['image_url', 'driving_video_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/latentsync',
    name: 'LatentSync',
    description: 'Latent-space audio lip sync.',
    credits: 14,
    time: '~35s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'lip-sync',
    mediaType: 'video',
    workflowType: 'lip-sync',
    uiGroup: 'generation',
    supports: ['audio_url', 'video_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/hallo2',
    name: 'Hallo2',
    description: 'Audio-driven portrait animation.',
    credits: 16,
    time: '~45s',
    icon: 'video',
    provider: 'fal-ai',
    category: 'lip-sync',
    mediaType: 'video',
    workflowType: 'lip-sync',
    uiGroup: 'generation',
    supports: ['audio_url', 'image_url'],
    defaults: {},
  },
  {
    id: 'fal-ai/sonic',
    name: 'Sonic (ByteDance)',
    description: 'High-quality audio lip sync by ByteDance.',
    credits: 18,
    time: '~50s',
    icon: 'video',
    badge: 'Quality',
    provider: 'fal-ai',
    category: 'lip-sync',
    mediaType: 'video',
    workflowType: 'lip-sync',
    uiGroup: 'generation',
    supports: ['audio_url', 'image_url'],
    defaults: {},
  },
];

export const TEXT_MODELS: StudioModel[] = [
  {
    id: 'google/gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    description: 'Fast and balanced text generation.',
    credits: 1,
    time: '~2s',
    icon: 'text',
    badge: 'Fast',
    provider: 'lovable-ai',
    category: 'text-generation',
    mediaType: 'text',
    workflowType: 'text-to-text',
    uiGroup: 'generation',
  },
  {
    id: 'google/gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    description: 'High-context reasoning model.',
    credits: 5,
    time: '~8s',
    icon: 'text',
    badge: 'Premium',
    provider: 'lovable-ai',
    category: 'text-generation',
    mediaType: 'text',
    workflowType: 'text-to-text',
    uiGroup: 'generation',
  },
  {
    id: 'openai/gpt-5-mini',
    name: 'GPT-5 Mini',
    description: 'Efficient general-purpose model.',
    credits: 3,
    time: '~4s',
    icon: 'text',
    provider: 'lovable-ai',
    category: 'text-generation',
    mediaType: 'text',
    workflowType: 'text-to-text',
    uiGroup: 'generation',
  },
  {
    id: 'openai/gpt-5',
    name: 'GPT-5',
    description: 'Highest capability model.',
    credits: 8,
    time: '~10s',
    icon: 'text',
    badge: 'Premium',
    provider: 'lovable-ai',
    category: 'text-generation',
    mediaType: 'text',
    workflowType: 'text-to-text',
    uiGroup: 'generation',
  },
];

export const getDefaultImageModel = () => imageGenerationModels[0].id;
export const getDefaultVideoModel = () => videoGenerationModels[0].id;
export const getDefaultAudioModel = () => AUDIO_MODELS[0].id;
export const getDefaultTextModel = () => TEXT_MODELS[0].id;

export const getModelById = (id: string): StudioModel | undefined => {
  return [...IMAGE_MODELS, ...VIDEO_MODELS, ...LIPSYNC_MODELS, ...AUDIO_MODELS, ...TEXT_MODELS].find((model) => model.id === id);
};

export const getModelsByType = (type: StudioModelMediaType): StudioModel[] => {
  switch (type) {
    case 'image':
      return IMAGE_MODELS;
    case 'video':
      return [...VIDEO_MODELS, ...LIPSYNC_MODELS];
    case 'audio':
      return AUDIO_MODELS;
    case 'text':
      return TEXT_MODELS;
    default:
      return [];
  }
};

export const getModelsByTypeAndGroup = (
  type: StudioModelMediaType,
  uiGroup: StudioModelUiGroup
): StudioModel[] => getModelsByType(type).filter((model) => model.uiGroup === uiGroup);

export const getLipsyncModels = (): StudioModel[] => LIPSYNC_MODELS;

// For dropdowns and quick pickers
export const IMAGE_MODEL_OPTIONS = IMAGE_MODELS.map((model) => ({ id: model.id, label: model.name }));
export const VIDEO_MODEL_OPTIONS = VIDEO_MODELS.map((model) => ({ id: model.id, label: model.name }));
export const LIPSYNC_MODEL_OPTIONS = LIPSYNC_MODELS.map((model) => ({ id: model.id, label: model.name }));
export const AUDIO_MODEL_OPTIONS = AUDIO_MODELS.map((model) => ({ id: model.id, label: model.name }));
export const TEXT_MODEL_OPTIONS = TEXT_MODELS.map((model) => ({ id: model.id, label: model.name }));
